(function(root){
const groups={solid:'A-001 正白,A-002 正黑,A-003 正紅,A-004 寶藍,A-005 正黃,A-061 機甲白,A-064 深灰,AF-001 消光白,AF-002 消光黑,AF-004 消光寶藍,A-013 森綠,A-018 黃綠,A-028 鈷藍,A-103 淺螢紅,A-104 淺螢藍,A-105 玉米黃',metal:'AM-05 機械金,AM-20 槍鐵,AX-21 星光銀,AM-33 金屬紅,AM-34 金屬寶藍,AM-36 金屬綠',dye:'A-040 透明桃紅,A-041 透明紅,A-042 透明橙,A-043 透明黃金,A-044 透明天藍,A-045 透明黃,A-047 透明紫,A-048 透明綠,A-049 透明寶藍,A-050 透明黑,A-051 透明深棕',other:'A-007 亮光透明,A-008 消光透明,AK-08 透明底漆,AK-31 灰色光澤底漆,MK-11 灰補土,MK-12 黑補土,MK-13 白補土,AK-05 增稠劑,AK-07 柔化介質,AK-14 金屬介質,AW-07 滲線基底,Z-01 水性稀釋液,Z-06 轉性稀釋液,D-01 硝基稀釋液,Z-08 緩乾劑,AK-42 金屬下地,AK-23 玻璃黑,AX-40 電鍍銀'};
const inventory=Object.entries(groups).flatMap(([type,s])=>s.split(',').map(x=>{const [id,...name]=x.split(' ');return{id,name:name.join(' '),type}}));
const aliases=[['クリアイエロー|透明黃|clear yellow','A-045'],['クリアレッド|透明紅|clear red','A-041'],['クリアグリーン|透明綠|clear green','A-048'],['コバルトブルー|鈷藍|cobalt blue','A-028'],['インディブルー|寶藍|indy blue','A-004'],['モンザレッド|monza red|red madder','A-003'],['シャインレッド|shine red',null],['RLM.?75.*|ウッドブラウン|ココアブラウン|木棕|可可棕|灰紫|wood brown|cocoa brown',null],['ホワイト|白色|正白|white','A-001'],['ブラック|黑色|正黑|black','A-002'],['グレー|灰色|gray|grey','A-064'],['ブルー|藍色|blue','A-004'],['レッド|紅色|red','A-003'],['イエロー|黃色|yellow','A-005'],['ゴールド|金色|gold','AM-05'],['シルバー|銀色|silver','AX-21']];
function normalize(s){return s.normalize('NFKC').replace(/[‐‑–—−]/g,'-').replace(/％/g,'%').replace(/\r/g,'').replace(/[ \t　]+/g,' ').trim()}
function map(name){const n=normalize(name);const code=n.match(/\b(A|AF|AM|AX|AK|MK|Z|D|AW)\s*-?\s*(\d{1,3})\b/i);if(code){const prefix=code[1].toUpperCase();const id=prefix+'-'+code[2].padStart(prefix==='A'||prefix==='AF'?3:2,'0');return inventory.find(p=>p.id===id)||null;} const entry=aliases.find(([r])=>new RegExp('^(?:'+r+')$','i').test(n.replace(/\s/g,'').toLowerCase())||new RegExp('^(?:'+r+')$','i').test(n));return entry&&entry[1]?inventory.find(p=>p.id===entry[1]):null;}
function parse(text){return normalize(text).split(/\n\s*\n/).filter(Boolean).map((block,i)=>{const lines=block.split('\n');let title='配色 '+(i+1);if(lines[0].includes(':')){const [a,...b]=lines[0].split(':');title=a;lines[0]=b.join(':')}else if(lines.length>1&&!/\d\s*%/.test(lines[0]))title=lines.shift();const raw=lines.join(' ').replace(/の塗装色[。.]?/g,'');const layer=/下地|底層|上罩|罩染|topcoat|undercoat|→/i.test(raw);const parts=raw.split(/[+＋→]/).filter(x=>x.trim()).map(s=>{s=s.trim();const m=s.match(/^(.*?)\s*[（(]?\s*(\d+(?:\.\d+)?)\s*%\s*[)）]?\s*$/);const tiny=/少量|small|small dose/i.test(s);return {name:(m?m[1]:s.replace(/[（(]?(少量|small dose|small)[)）]?/ig,'')).replace(/^(下地|底層|上罩|罩染|topcoat|undercoat)\s*/i,'').trim(),amount:m?Number(m[2]):null,tiny};});return{title,raw,layer,parts};})}
function suggest(row,owned,total){const warnings=[];const items=row.parts.map(p=>{const paint=map(p.name);if(!paint)warnings.push('無已核對替代色：'+p.name);else if(!owned.includes(paint.id))warnings.push('缺少庫存：'+paint.id+' '+paint.name);if(p.amount===null&&!p.tiny)warnings.push('比例未辨識：'+p.name);if(p.amount!==null&&(p.amount<=0||p.amount>100))warnings.push('比例超出範圍：'+p.name);return {...p,paint,ml:p.amount===null?null:total*p.amount/100}});const sum=items.reduce((s,p)=>s+(p.amount||0),0);if(!row.layer&&Math.abs(sum-100)>.05)warnings.push('比例合計 '+sum+'%，請核對原圖；不自動補足');if(row.layer&&items.some(p=>p.amount!==100||p.tiny))warnings.push('分層配方需人工核對每層內容');if(!row.layer&&items.some(p=>p.paint?.type==='dye')&&items.some(p=>p.paint&&p.paint.type!=='dye'))warnings.push('透明染料與實色／金屬混合：需另驗證相容性與效果');if(items.some(p=>p.paint?.type==='other'))warnings.push('底漆／助劑／電鍍漆不作一般調色替代');return{...row,items,warnings,status:warnings.length?'待確認':'未實測起始配方'};}
const sample='本體白色：ホワイト(100%)\n\n本體淺灰：ホワイト(95%)+グレー(5%)+ブルー(少量)\n\n本體紅色：モンザレッド(60%)+シャインレッド(40%)\n\n本體深紅：モンザレッド(90%)+ココアブラウン(10%)\n\n腹部灰色：RLM75グレーバイオレット(65%)+ホワイト(35%)+ウッドブラウン(少量)\n\n胸部深灰：ブラック(70%)+ホワイト(30%)\n\n刀身金色：下地ゴールド(100%)→クリアイエロー(100%)';
const api={inventory,parse,suggest,map,sample};root.PaintGuide=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window==='undefined'?globalThis:window);
